INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('bd6e0388-5d0c-11eb-b8ed-0897988520bf','07RLE_02GET_PARAMETERS00','http://host/api/reporteErroresLogEjecucion','REPORTE_ERRORES_LOG_EJECUCION','consultarReporteLogEjecucionDinamico','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarReporteLogEjecucionDinamico','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','18:51:26',NULL,NULL),
	 ('6684f077-5d0c-11eb-b8ed-0897988520bf','07RLE_02GET_GET02','http://host/api/reporteErroresLogEjecucion','REPORTE_ERRORES_LOG_EJECUCION','consultarReporteLogEjecucionDinamico','GET','GET','No se puede encontrar datos con los parámetros establecidos, establecer parámetros de acuero a los datos existentes','There is/are no record(s) for log execution report with the parameter(s) set','2021-01-22','18:49:00',NULL,NULL),
	 ('3cbc6232-5d0c-11eb-b8ed-0897988520bf','07RLE_02GET_GETPARAMETER01','http://host/api/reporteErroresLogEjecucion','REPORTE_ERRORES_LOG_EJECUCION','consultarReporteLogEjecucionDinamico','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint consultarErroresLogEjecucion','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-22','18:47:50',NULL,NULL),
	 ('460b0cf3-5d0a-11eb-b8ed-0897988520bf','06ELE_04DELETE_PARAMETER00','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','eliminarErrorLogEejecucionById','DELETE','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarErroresLogEjecucion','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','18:33:47',NULL,NULL),
	 ('e2710f67-5d09-11eb-b8ed-0897988520bf','06ELE_04DELETE_DELETE02','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','eliminarErrorLogEejecucionById','DELETE','DELETE','No se puede eliminar el registro con ID_ERROR establecido, comunicarse con el administrador del microservicio','The register with ID_ERROR: ${data.id_regla} could not be deleted','2021-01-22','18:31:00',NULL,NULL),
	 ('9dc59f4b-5d09-11eb-b8ed-0897988520bf','06ELE_04DELETE_GET01','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','eliminarErrorLogEejecucionById','DELETE','GET','No se puede encontrar el registro con ID_ERROR para ser eliminado, establecer un ID_ERROR de acuerdo a los datos disponibles','The register with ID_ERROR: ${data.id_error} was not found','2021-01-22','18:29:04',NULL,NULL),
	 ('c6f298cc-5cfd-11eb-b8ed-0897988520bf','06ELE_03put_PARAMETER00','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','actualizarErrorLogEjecucionById','PUT','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint actualizarErrorLogEjecucionById','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','17:04:19','2021-01-22','17:22:00'),
	 ('f6aecfb3-5cfc-11eb-b8ed-0897988520bf','06ELE_03PUT_PUT03','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','actualizarErrorLogEjecucionById','PUT','OUT','No se puede actaulizar el tipo de error, comunicarse con el administrador del microservicio','The register with ID_ERROR: ${data.id_error} could not be updated','2021-01-22','16:58:30',NULL,NULL),
	 ('d24bebae-5cfc-11eb-b8ed-0897988520bf','06ELE_03PUT_GET02','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','actualizarErrorLogEjecucionById','PUT','GET','No se puede actaulizar por que hay un tipo error similar ya registrado, debe cambiar la configuración del error','The error type with ID_ERROR: ${data.id_error} AND CODIGO_ERROR: ${data.codigo_error} already exist in the error typer with ID_ERROR: ${existenciaReglaJson.existenciaErrorJson}','2021-01-22','16:57:29',NULL,NULL),
	 ('9cc655e6-5cfc-11eb-b8ed-0897988520bf','06ELE_03PUT_GET01','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','actualizarErrorLogEjecucionById','PUT','GET','No se puede encontrar el registro con ID_ERROR para ser actualizado, debe establecer un ID_ERROR según los datos disponibles','The register with ID_ERROR: ${data.id_regla} was not found','2021-01-22','16:55:59',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('5d73f919-5cf9-11eb-b8ed-0897988520bf','06ELE_02GET_GET02','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','consultarErroresLogEjecucion','GET','GET','Con los parámetros establecidos no hay datos para tipo de errores, se debe establecer otros parámetros segun los datos disponibles','There is/are no record(s) for log execution log with the parameter(s) set','2021-01-22','16:32:44',NULL,NULL),
	 ('2a3667b7-5cf9-11eb-b8ed-0897988520bf','06ELE_02GET_GETPARAMETER01','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','consultarErroresLogEjecucion','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint consultarErroresLogEjecucion','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-22','16:31:18',NULL,NULL),
	 ('3e1c5a57-5cf8-11eb-b8ed-0897988520bf','06ELE_02GET_PARAMETER00','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','consultarErroresLogEjecucion','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarErroresLogEjecucion','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','16:24:42',NULL,NULL),
	 ('229cbf1d-5cf8-11eb-b8ed-0897988520bf','06ELE_01POST_PARAMETER00','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','crearErroresLogEjecucion','POST','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint crearErroresLogEjecucion','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','16:23:56',NULL,NULL),
	 ('fe8267df-5cf7-11eb-b8ed-0897988520bf','06ELE_01POST_POST02','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','crearErroresLogEjecucion','POST','POST','No se puede crear el tipo de error, comunicarse con el administrador del microservicio','The error type with CODIGO_ERROR: ${data.codigo_error} could not be created','2021-01-22','16:22:56',NULL,NULL),
	 ('a5ac502e-5cf7-11eb-b8ed-0897988520bf','06ELE_01POST_GET01','http://host/api/erroresLogEjecucion','ERRORES_LOG_EJECUCION','crearErroresLogEjecucion','POST','GET','Existe un tipo error similar con las características dadas','The error type register with CODIGO_ERROR: ${data.codigo_error} and URL_ENDPOINT: ${data.URL_ENDPOINT} and MODULO: ${data.modulo} and ENDPOINT ${data.endpoint} and METODO: ${data.metodo} already exist','2021-01-22','16:20:27',NULL,NULL),
	 ('e2f34712-5ced-11eb-b8ed-0897988520bf','05DNS_02GET_GET02','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','consutarDatosNodoSensorDinamico','GET','GET','No hay registros con los parametros establecidos, se debe establecer parameters de acuerdo a los datos disponibles','There is/are no record(s) for data sensor node with the parameter(s) set','2021-01-22','15:10:34',NULL,NULL),
	 ('b40dc392-5ced-11eb-b8ed-0897988520bf','05DNS_02GET_GETPARAMETER01','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','consutarDatosNodoSensorDinamico','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint consutarDatosNodoSensorDinamico','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-22','15:09:16',NULL,NULL),
	 ('11139440-5ced-11eb-b8ed-0897988520bf','05DNS_01POST_POST05','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','crearDatoNodoSensor','POST','POST','No se puede insertar el dato, comunicarse con el administrador del microservicio','The data: {${nombreVariable}: ${valorDato}} could not be created for the sensor node with ID_NODO_SENSOR: ${idNodoSensor}','2021-01-22','15:04:42',NULL,NULL),
	 ('9785e4f9-5cec-11eb-b8ed-0897988520bf','05DNS_01POST_GET04','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','crearDatoNodoSensor','POST','GET','El nodo sensor no esta configurado para publicar en dichas variables, se debe configurar el nodo sensor con la varibles necesarias y que ya esten registradas.','The variable(s): ${variablesErrorArray.toString().replace('','', '', '')} is/are not allowed to POST for the sensor nodo with ID_NODO_SENSOR: ${data.id_nodo_sensor}','2021-01-22','15:01:18',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('59666eeb-5cec-11eb-b8ed-0897988520bf','05DNS_01POST_GET03','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','crearDatoNodoSensor','POST','GET','El token del nodo sensor que desea insertar el dato no esta activo, se debe actualizar el nodo sensor y cambiar el estado a true.','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} is disabled','2021-01-22','14:59:34',NULL,NULL),
	 ('33edaf3e-5cec-11eb-b8ed-0897988520bf','05DNS_01POST_GET02','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','crearDatoNodoSensor','POST','GET','El token del nodo sensor que desea insertar el dato no cumple con el token del registro original, se debe consultar el nodo sensor con el ID_NODO_SENSOR requeido y comprobar el token generado','The token of the sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} is not the same','2021-01-22','14:58:31',NULL,NULL),
	 ('f7df5ebc-5ceb-11eb-b8ed-0897988520bf','05DNS_01POST_GET01','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','crearDatoNodoSensor','POST','GET','Si el nodo sensor no existe no se puede regristrar datos con el ID_NODO_SENSOR y TOKEN establecidos, se debe registrar el nodo sensor','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} was not found','2021-01-22','14:56:51',NULL,NULL),
	 ('c2974809-5ceb-11eb-b8ed-0897988520bf','05DNS_02GET_PARAMETER00','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','consutarDatosNodoSensorDinamico','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint eliminarReglaNodoSensorById','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','14:55:21',NULL,NULL),
	 ('b8ddef6b-5ceb-11eb-b8ed-0897988520bf','05DNS_01POST_PARAMETER00','http://host/api/datosNodoSensor','DATOS_NODO_SENSOR','crearDatoNodoSensor','POST','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint eliminarReglaNodoSensorById','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','14:55:05',NULL,NULL),
	 ('86271de3-5cea-11eb-b8ed-0897988520bf','04RVNS_04DELETE_PARAMETER00','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','eliminarReglaNodoSensorById','DELETE','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint eliminarReglaNodoSensorById','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','14:46:30',NULL,NULL),
	 ('3dd9a227-5cea-11eb-b8ed-0897988520bf','04RVNS_04DELETE_DELETE02','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','eliminarReglaNodoSensorById','DELETE','DELETE','El registro deseado no se puede eliminar, comunicarse con el administrador del microservicio','The register with ID_REGLA: ${data.id_regla} could not be deleted','2021-01-22','14:44:29',NULL,NULL),
	 ('f9e988e1-5ce9-11eb-b8ed-0897988520bf','04RVNS_04DELETE_GET01','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','eliminarReglaNodoSensorById','DELETE','GET','El registro deseado para eliminar no es encotrado, seleccionar un ID_REGLA disponible en los datos','The register with ID_REGLA: ${data.id_regla} was not found','2021-01-22','14:42:35',NULL,NULL),
	 ('cf9b54bb-5ce6-11eb-b8ed-0897988520bf','04RVNS_03PUT_PUT07','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','PUT','El registro deseado no se puede actualizar, comunicarse con el administrador del microservicio','The register with ID_REGLA: ${data.id_regla} could not be updated','2021-01-22','14:19:56',NULL,NULL),
	 ('aba2ed28-5ce6-11eb-b8ed-0897988520bf','04RVNS_03PUT_GET06','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','GET','La configuración de regla no se puede crear hasta que no se hayan configurado las variables con nodo sensor','The variable configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and NOMBRE_VARIABLE: ${data.nombre_variable} has not been associated in variable configuration, please set up this configuration','2021-01-22','14:18:55',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('81ba5bba-5ce6-11eb-b8ed-0897988520bf','04RVNS_03PUT_GET05','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','GET','Si la regla que se quiere actualizar uan regla y si existe alguna simimilar (NOMBRE_VARIABLE Y ID_NODO_SENSOR) no se puede actualizar el registro, se debe seleccionar un NOMBRE_VARIABLE o ID_NODO_SENSOR diferente de acuerdo a los registros existentes de cada uno','The rule configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and ID_VARIABLE: ${existenciaReglaJson.ID_VARIABLE} and NOMBRE_VARIABLE: ${data.nombre_variable} already exist in the rule configuration with ID_REGLA: ${existenciaReglaJson.ID_REGLA}','2021-01-22','14:17:45',NULL,NULL),
	 ('0c352cb1-5ce6-11eb-b8ed-0897988520bf','04RVNS_03PUT_GET04','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','GET','La variable que se desea configurar en reglas con el nodo sensor no existe, seleccionar una de las variables ya estan registradas','The variable with NOMBRE_VARIABLE: ${data.nombre_variable} was not found','2021-01-22','14:14:28',NULL,NULL),
	 ('f0aba4ce-5ce5-11eb-b8ed-0897988520bf','04RVNS_03PUT_GET03','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','GET','El nodo sensor que se desea configurar en reglas no existe, seleccionar uno de los nodos sensores ya estan registrados','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} was not found','2021-01-22','14:13:41',NULL,NULL),
	 ('d679905a-5ce5-11eb-b8ed-0897988520bf','04RVNS_03PUT_GET02','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','GET','El nodo sensor que se desea configurar en reglas no existe, seleccionar uno de los nodos sensores ya estan registrados','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} and variable with ID_VARIABLE: ${data.nombre_variable} were not found','2021-01-22','14:12:58',NULL,NULL),
	 ('a7b74caf-5ce5-11eb-b8ed-0897988520bf','04RVNS_03PUT_GET01','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','GET','El registro con ID_REGLA no es encontrado, por lo tanto, no se puede actualizar, se debe seleccionar un ID_REGLA disponible en los datos','The register with ID_REGLA: ${data.id_regla} was not found','2021-01-22','14:11:39',NULL,NULL),
	 ('731ff410-5ce5-11eb-b8ed-0897988520bf','04RVNS_03PUT_PARAMETER00','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','actualizarReglaNodoSensorById','PUT','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint actualizarReglaNodoSensorById','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','14:10:11',NULL,NULL),
	 ('24aa48f5-5ce5-11eb-b8ed-0897988520bf','04RVNS_02GET_PARAMETER00','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','consultarReglasNodoSensorDinamico','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarReglasNodoSensorDinamico','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','14:07:59',NULL,NULL),
	 ('9f6c72b0-5ce4-11eb-b8ed-0897988520bf','04RVNS_02GET_GET02','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','consultarReglasNodoSensorDinamico','GET','GET','Con los parametros y condicione establecidas no existen datos para consultar reglas creada, establecer otras condiciones segun los datos disponibles en reglas','There is/are no record(s) for rule configuration with the parameter(s) set','2021-01-22','14:04:16',NULL,NULL),
	 ('633543f0-5ce4-11eb-b8ed-0897988520bf','04RVNS_02GET_GETPARAMETER01','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','consultarReglasNodoSensorDinamico','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint consultarReglasNodoSensorDinamico','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-22','14:02:35',NULL,NULL),
	 ('2e8cbc63-5ce4-11eb-b8ed-0897988520bf','04RVNS_01POST_PARAMETER00','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint crearReglaNodoSensor','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','14:01:06',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('6e42f7f1-5ce3-11eb-b8ed-0897988520bf','04RVNS_01POST_POST06','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','POST','No se puede crear la configuracion de regla que se quiere ingresar, comunicarse con el administrador del microservicio','The rule configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and ID_VARIABLE: ${existenciaReglaJson.ID_VARIABLE} and NOMBRE_VARIABLE: ${data.nombre_variable} could not be created','2021-01-22','13:55:44',NULL,NULL),
	 ('3dded2d4-5ce3-11eb-b8ed-0897988520bf','04RVNS_01POST_GET05','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','GET','La configuración de regla no se puede crear hasta que no se hayan configurado las variables con nodo sensor','The variable configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and NOMBRE_VARIABLE: ${data.nombre_variable} has not been associated in variable configuration, please set up this configuration','2021-01-22','13:54:23',NULL,NULL),
	 ('f6f33e4e-5ce2-11eb-b8ed-0897988520bf','04RVNS_01POST_GET04','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','GET','La configuracion de regla ya exisite, se debe seleccionar un nodo sesnor o variable diferente que no esten registrado en las reglas','The rule configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and ID_VARIABLE: ${existenciaReglaJson.ID_VARIABLE} and NOMBRE_VARIABLE: ${data.nombre_variable} already exist','2021-01-22','13:52:24',NULL,NULL),
	 ('a31d4a06-5ce2-11eb-b8ed-0897988520bf','04RVNS_01POST_GET03','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','GET','La variable que se desea configurar en reglas con el nodo sensor no existe, seleccionar una de las variables ya estan registradas','The variable with NOMBRE_VARIABLE: ${data.nombre_variable} was not found','2021-01-22','13:50:03',NULL,NULL),
	 ('80cc8724-5ce2-11eb-b8ed-0897988520bf','04RVNS_01POST_GET02','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','GET','El nodo sensor que se desea configurar en reglas no existe, seleccionar uno de los nodos sensores ya estan registrados','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} was not found','2021-01-22','13:49:05',NULL,NULL),
	 ('57295582-5ce2-11eb-b8ed-0897988520bf','04RVNS_01POST_GET01','http://host/api/reglasNodoSensor','REGLAS_VARIABLES_NODO_SENSOR','crearReglaNodoSensor','POST','GET','El nodo sensor y la variable que desean configurar en las reglas no existe, seleccionar uno de los nodos sensores y variable que ya estan registrados','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} and variable with ID_VARIABLE: ${data.id_variable} were not found','2021-01-22','13:47:55',NULL,NULL),
	 ('51058147-5cd7-11eb-b8ed-0897988520bf','03CVNS_04DELETE_PARAMETER00','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','eliminarConfiguracionVariablesNodoSensorByIDConfiguracion','DELETE','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint eliminarConfiguracionVariablesNodoSensorByIDConfiguracion','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','12:29:01',NULL,NULL),
	 ('df9d117b-5cd6-11eb-b8ed-0897988520bf','03CVNS_04DELETE_DELETE02','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','eliminarConfiguracionVariablesNodoSensorByIDConfiguracion','DELETE','DELETE','El registro ID_CONFIGRACION no puede ser eliminado, comunicarse con el administrador del microservicio','The register with ID_CONFIGURACION: ${data.id_configuracion} could not be deleted','2021-01-22','12:25:50',NULL,NULL),
	 ('a4c76d82-5cd6-11eb-b8ed-0897988520bf','03CVNS_04DELETE_GET01','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','eliminarConfiguracionVariablesNodoSensorByIDConfiguracion','DELETE','GET','El registro ID_CONFIGRACION para eliminar no es encontrado, se debe pasar un ID_CONFIGURACION que este registrado','The register with ID_CONFIGURACION: ${data.id_configuracion} was not found','2021-01-22','12:24:12',NULL,NULL),
	 ('58ef21e4-5cd6-11eb-b8ed-0897988520bf','03CVNS_02GET_PARAMETER00','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','consultarConfiguracionesVariablesNodoSensorDinamico','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarConfiguracionesVariablesNodoSensorDinamico','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','12:22:04',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('ee2d29c8-5cd5-11eb-b8ed-0897988520bf','03CVNS_02GET_GET02','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','consultarConfiguracionesVariablesNodoSensorDinamico','GET','GET','Con los parametros y condicione establecidas no existen datos, estableces otras conndiciones segun los datos disponibles','There is/are no record(s) for variable configuration with the parameter(s) set','2021-01-22','12:19:05',NULL,NULL),
	 ('ba890420-5cd5-11eb-b8ed-0897988520bf','03CVNS_02GET_GETPARAMETER01','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','consultarConfiguracionesVariablesNodoSensorDinamico','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint consultarConfiguracionesVariablesNodoSensorDinamico','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-22','12:17:39',NULL,NULL),
	 ('fdf05aaa-5cd4-11eb-b8ed-0897988520bf','03CVNS_01POST_PARAMETER00','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','crearConfiguracioVariableNodoSensor','POST','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint crearConfiguracioVariableNodoSensor','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','12:12:22',NULL,NULL),
	 ('8b39b934-5cd4-11eb-b8ed-0897988520bf','03CVNS_01POST_POST05','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','crearConfiguracioVariableNodoSensor','POST','POST','La configuración ingresada no se puede crear, comunicarse con el administrador del microservicio','The variable configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and ID_VARIABLE: ${data.id_variable} could not be created','2021-01-22','12:09:10',NULL,NULL),
	 ('68ac21d9-5cd4-11eb-b8ed-0897988520bf','03CVNS_01POST_GET04','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','crearConfiguracioVariableNodoSensor','POST','GET','La configuración ingresada ya existe, seleccionar otro nodo sensor o variable que se encuentren resgitrados','The variable configuration with ID_NODO_SENSOR: ${data.id_nodo_sensor} and ID_VARIABLE: ${existenciaConfiguracionVarJson.ID_VARIABLE} and NOMBRE_VARIABLE: ${data.nombre_variable} already exist','2021-01-22','12:08:12',NULL,NULL),
	 ('3c61fce8-5cd4-11eb-b8ed-0897988520bf','03CVNS_01POST_GET03','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','crearConfiguracioVariableNodoSensor','POST','GET','La variable que se desea configurar  con el nodo sensor no existe, seleccionar una de las variables ya estan registradas','The variable with NOMBRE_VARIABLE: ${data.nombre_variable} was not found','2021-01-22','12:06:58',NULL,NULL),
	 ('1bac1684-5cd4-11eb-b8ed-0897988520bf','03CVNS_01POST_GET02','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','crearConfiguracioVariableNodoSensor','POST','GET','El nodo sensor que se desea configurar  con la variable no existe, seleccionar uno de los nodos sensores ya estan registrados','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} was not found','2021-01-22','12:06:03',NULL,NULL),
	 ('f899e69d-5cd3-11eb-b8ed-0897988520bf','03CVNS_01POST_GET01','http://host/api/configuracionVariablesNodoSensor','CONFIGURACION_VARIABLES_NODO_SENSOR','crearConfiguracioVariableNodoSensor','POST','GET','El nodo sensor y la variable que desean configurar no existe, seleccionar uno de los nodos sensores y variable que ya estan registrados','The sensor node with ID_NODO_SENSOR: ${data.id_nodo_sensor} and variable with ID_VARIABLE: ${data.id_variable} were not found','2021-01-22','12:05:04',NULL,NULL),
	 ('4768f10b-5ccf-11eb-b8ed-0897988520bf','02VNS_03PUT_PARAMETER00','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint actualizarVariableByID','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','11:31:29',NULL,NULL),
	 ('ffcbb8f3-5cce-11eb-b8ed-0897988520bf','02VNS_04DELETE_PARAMETER00','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint eliminarVariableByIDByNombreVariable','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','11:29:28',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('3a1bdf32-5cce-11eb-b8ed-0897988520bf','02VNS_04DELETE_DELETE06','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','DELETE','El registro de variable que se quiere eliminar con NOMBRE_VARIABLE no se puede eliminar, comunicarse con el administrador del microservicio','The register with NOMBRE_VARIABLE: ${data.nombre_variable} could not be deleted','2021-01-22','11:23:57',NULL,NULL),
	 ('23dfd65b-5cce-11eb-b8ed-0897988520bf','02VNS_04DELETE_DELETE05','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','DELETE','El registro de variable que se quiere eliminar con ID_VARIABLE no se puede eliminar, comunicarse con el administrador del microservicio','The register with ID_VARIABLE: ${data.id_variable} could not be deleted','2021-01-22','11:23:19',NULL,NULL),
	 ('0ddff810-5cce-11eb-b8ed-0897988520bf','02VNS_04DELETE_DELETE04','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','DELETE','El registro de variable que se quiere eliminar con ID_VARIABLE O NOMBRE_VARIABLE no se puede eliminar, comunicarse con el administrador del microservicio','The register with ID_VARIABLE: ${data.id_variable} and NOMBRE_VARIABLE: ${data.nombre_variable} could not be deleted','2021-01-22','11:22:43',NULL,NULL),
	 ('daba7b94-5ccd-11eb-b8ed-0897988520bf','02VNS_04DELETE_GET03','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','GET','El registro de variable que se quiere eliminar con NOMBRE_VARIABLE no existe, se debe pasar NOMBRE_VARIABLE que este disponibles en variable','The register with NOMBRE_VARIABLE: ${data.nombre_variable} was not found','2021-01-22','11:21:17',NULL,NULL),
	 ('bdab73f8-5ccd-11eb-b8ed-0897988520bf','02VNS_04DELETE_GET02','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','GET','El registro de variable que se quiere eliminar con ID_VARIABLE no existe, se debe pasar ID_VARIABLE que este disponibles en variable','The register with ID_VARIABLE: ${data.id_variable} was not found','2021-01-22','11:20:28',NULL,NULL),
	 ('a2e6b6c5-5ccd-11eb-b8ed-0897988520bf','02VNS_04DELETE_GET01','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','eliminarVariableByIDByNombreVariable','DELETE','GET','El registro de variable que se quiere eliminar con ID_VARIABLE o NOMBRE VARIABLE no existe, se debe pasar uno de los dos datos que este disponibles en variable','The register with ID_VARIABLE: ${data.id_variable} and NOMBRE_VARIABLE: ${data.nombre_variable} was not found','2021-01-22','11:19:43',NULL,NULL),
	 ('9d5eb976-5ccc-11eb-b8ed-0897988520bf','02VNS_03PUT_PUT06','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','PUT','La variable con el ID_VARIABLE no se puede actualizar, comunicarse con el administrador del microservicio','The register with ID_VARIABLE: ${data.id_variable} could not be updated','2021-01-22','11:12:24',NULL,NULL),
	 ('02697a54-5ccc-11eb-b8ed-0897988520bf','02VNS_03PUT_GET05','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','GET','El nombre de la variable que se quiere actualizar ya existe en otra variable, el nombre de la variable debe ser único, se debe escger otro nombre de variable','The variable with ID_VARIABLE: ${data.id_variable} and NOMBRE_VARIABLE: ${data.nombre_variable} already exist in the variable register with NOMBRE_VARIABLE: ${existenciaVariableJson.ID_VARIABLE}','2021-01-22','11:08:04',NULL,NULL),
	 ('c35af58e-5ccb-11eb-b8ed-0897988520bf','02VNS_03PUT_DATA04','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','DATA','El rango mínimo de la variable que se quiere actualizar es igual al rango máximo establecido, establecer el rango mínimo y rango máximo de la variable adecuadamente.','The minimun rank: ${data.rango_min} is the samse as maximun rank: ${data.rango_max}','2021-01-22','11:06:19',NULL,NULL),
	 ('a4b03332-5ccb-11eb-b8ed-0897988520bf','02VNS_03PUT_DATA03','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','DATA','El rango mínimo de la variable que se quiere actualizar es mayor al rango máximo establecido, establecer el rango mínimo y rango máximo de la variable adecuadamente','The minimun rank: ${data.rango_min} is greater than maximun rank: ${data.rango_max}','2021-01-22','11:05:27',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('6df491f7-5ccb-11eb-b8ed-0897988520bf','02VNS_03PUT_GET02','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','GET','La variable que se busca por ID_VARIABLE no existe, establece un ID_VARIABLE disposnible en los datos','The register with ID_VARIABLE: ${data.id_variable} was not found','2021-01-22','11:03:55',NULL,NULL),
	 ('0caf50cf-5ccb-11eb-b8ed-0897988520bf','02VNS_03PUT_DATA01','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','actualizarVariableByID','PUT','DATA','El valor del parámetro NOMBRE_VARIABLE no cumple con los caractores permitidos, revisar la documentación del endpoint crearVariablesNodoSensor','The register with NOMBRE_VARIABLES: ${data.nombre_variable} contains characters not allowed, letters, numbers and underscore are allowed ','2021-01-22','11:01:12',NULL,NULL),
	 ('e93ba332-5cc7-11eb-b8ed-0897988520bf','02VNS_02GET_PARAMETER00','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','consultarVariablesNodoSensorDinamico','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarVariablesNodoSensorDinamico','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','10:38:44',NULL,NULL),
	 ('30accf08-5cc7-11eb-b8ed-0897988520bf','02VNS_02GET_GET02','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','consultarVariablesNodoSensorDinamico','GET','GET','No hay datos con los parámetros fijados, establecer otros de acuerdo a los datos disponibles ','There is/are no record(s) for variables sensor node with the parameter(s) set','2021-01-22','10:33:34',NULL,NULL),
	 ('bfeabd3a-5cc6-11eb-b8ed-0897988520bf','02VNS_02GET_GETPARAMETER01','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','consultarVariablesNodoSensorDinamico','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint consultarVariablesNodoSensorDinamico','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-22','10:30:25',NULL,NULL),
	 ('8c9dc944-5cc3-11eb-b8ed-0897988520bf','02VNS_01POST_PARAMETER00','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','crearVariablesNodoSensor','POST','PARAMETERS','Los parámetros ingresados en la petición no son los correctos; pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint crearVariablesNodoSensor','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-22','10:07:31',NULL,NULL),
	 ('04bec9b7-5cc2-11eb-b8ed-0897988520bf','02VNS_01POST_POST04','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','crearVariablesNodoSensor','POST','POST','La variable no puede ser agregada, contactarse con el administrador del microservicio','The variable: ${data.nombre_variable} could not be created','2021-01-22','09:56:33',NULL,NULL),
	 ('cb612e8a-5cc1-11eb-b8ed-0897988520bf','02VNS_01POST_DATA03','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','crearVariablesNodoSensor','POST','DATA','El rango mínimo de la variable que se quiere es igual al rango máximo establecido, establecer el rango mínimo y rango máximo de la variable adecuadamente.','The minimun rank: ${data.rango_min} is the samse as maximun rank: ${data.rango_max}','2021-01-22','09:54:57',NULL,NULL),
	 ('9260c519-5cc1-11eb-b8ed-0897988520bf','02VNS_01POST_DATA02','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','crearVariablesNodoSensor','POST','DATA','El rango mínimo de la variable que se quiere es mayor al rango máximo establecido, establecer el rango mínimo y rango máximo de la variable adecuadamente.','`The minimun rank: ${data.rango_min} is greater than maximun rank: ${data.rango_max}','2021-01-22','09:53:21',NULL,NULL),
	 ('54425a92-5cc1-11eb-b8ed-0897988520bf','02VNS_01POST_GET01','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','crearVariablesNodoSensor','POST','GET','La variable que se quiere agregar con ese NOMBRE_VARIABLES ya existe, seleccionar un NOMBRE_VARIABLES distinto a los que ya existe','The variable: ${data.nombre_variable} already exist','2021-01-22','09:51:37',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('6d9a684c-5cc0-11eb-b8ed-0897988520bf','02VNS_01POST_DATA01','http://host/api/variablesNodoSensor','VARIABLES_NODO_SENSOR','crearVariablesNodoSensor','POST','DATA','El valor del parámetro NOMBRE_VARIABLE no cumple con los caractores permitidos, revisar la documentación del endpoint crearVariablesNodoSensor','The register with NOMBRE_VARIABLES: ${data.nombre_variable} contains characters not allowed, letters, numbers and underscore are allowed ','2021-01-22','09:45:10',NULL,NULL),
	 ('aff6e3a3-5c1f-11eb-80f6-0897988520bf','01NS_04DELETE_PARAMETERS00','http://host/api/nodoSensor','NODO_SENSOR','eliminarNodoSensor','DELETE','PARAMETERS','Los parámetros ingresados en la petición no son los correctos y que pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint eliminarNodoSensor','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-21','14:34:33',NULL,NULL),
	 ('64fc15e0-5c1f-11eb-80f6-0897988520bf','01NS_03PUT_PARAMETERS00','http://host/api/nodoSensor','NODO_SENSOR','actualizarNodoSensor','PUT','PARAMETERS','Los parámetros ingresados en la petición no son los correctos y que pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint actualizarNodoSensor','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-21','14:32:27',NULL,NULL),
	 ('b482dd0c-5c1e-11eb-80f6-0897988520bf','01NS_02GET_PARAMETERS00','http://host/api/nodoSensor','NODO_SENSOR','consultarNodoSensorDinamico','GET','PARAMETERS','Los parámetros ingresados en la petición no son los correctos y que pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint consultarNodoSensorDinamico','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-21','14:27:31',NULL,NULL),
	 ('048be760-5c1d-11eb-80f6-0897988520bf','01NS_01POST_PARAMETERS00','http://host/api/nodoSensor','NODO_SENSOR','crearNodoSensor','POST','POST','Los parámetros ingresados en la petición no son los correctos y que pueden faltar parámetros o pueden estar mal escritos, revisar la documentación del endpoint crearNodoSensor','${verificarParametro.messageFaltantes} or ${verificarParametro.messageMalEscritos}, please set a all required parameters','2021-01-21','14:15:26',NULL,NULL),
	 ('2d20f62e-5c08-11eb-80f6-0897988520bf','01NS_02GET_GET02','http://host/api/nodoSensor','NODO_SENSOR','consultarNodoSensorDinamico','GET','GET','No hay datos con los parametros fijado, revisar los parametros','There is/are no record(s) for sensor node with the parameter(s) set','2021-01-21','11:46:15',NULL,NULL),
	 ('2364dcac-5c05-11eb-80f6-0897988520bf','01NS_02GET_GETPARAMETERS01','http://host/api/nodoSensor','NODO_SENSOR','consultarNodoSensorDinamico','GET','GETPARAM','Los parametros del JSON condicion pueden estar mal escritos o pueden faltar parametros, revisar la documentación del endpoint','${verificarParametrosCondiciones.messageFaltantes} or ${verificarParametrosCondiciones.messageMalEscritos} in the condition: ${whereKeys[i].toUpperCase()}, please set a all required parameters','2021-01-21','11:24:30',NULL,NULL),
	 ('52315eb4-5b9a-11eb-8137-0897988520bf','01NS_04DELETE_DELETE02','http://host/api/nodoSensor','NODO_SENSOR','eliminarNodoSensor','DELETE','DELETE','El nodo sensor no con id fijado no se puede eliminar, contactarse con el administrador del microservicio','The register with ID: ${data.id_nodo_sensor} could not be deleted','2021-01-20','22:39:52',NULL,NULL),
	 ('1dd45456-5b9a-11eb-8137-0897988520bf','01NS_04DELETE_GET01','http://host/api/nodoSensor','NODO_SENSOR','eliminarNodoSensor','DELETE','GET','El nodo sensor no con id fijado no es encontrado, por lo tanto no se puede eliminar','The register with ID: ${data.id_nodo_sensor} was not found','2021-01-20','22:38:24',NULL,NULL),
	 ('de3490ff-5b99-11eb-8137-0897988520bf','01NS_03PUT_PUT02','http://host/api/nodoSensor','NODO_SENSOR','actualizarNodoSensor','PUT','PUT','El nodo sensor no se puede actualizar, por favor contactarse con el administrador del microservicio','The register with ID: ${data.id_nodo_sensor} could not be updated','2021-01-20','22:36:38',NULL,NULL);
INSERT INTO ERRORES_LOG_EJECUCION (ID_ERROR,CODIGO_ERROR,URL_ENDPOINT,MODULO,ENDPOINT,METODO_PRIMARIO,METODO_SECUNDARIO,DETALLES,MENSAJE_PANTALLA,FECHA_CREACION,HORA_CREACION,FECHA_ACTUALIZACION,HORA_ACTUALIZACION) VALUES
	 ('e6903567-5b98-11eb-8137-0897988520bf','01NS_03PUT_GET01','http://host/api/nodoSensor','NODO_SENSOR','actualizarNodoSensor','PUT','GET','El nodo sensor no con id fijado no es encontrado, por lo tanto no se puede actualizar','The register with ID: ${data.id_nodo_sensor} was not found','2021-01-20','22:29:42',NULL,NULL),
	 ('3b58641b-5b98-11eb-8137-0897988520bf','01NS_01POST_POST01','http://host/api/nodoSensor','NODO_SENSOR','crearNodoSensor','POST','POST','El nodo sensor no puede ser creado, contactarse con en el administrador de este microservicio','The node sensor could not be created','2021-01-20','22:24:55',NULL,NULL);