/*TABLA USER*/
DROP TABLE IF EXISTS `USUARIOS`;
CREATE TABLE `USUARIOS` (
  `ID_USUARIO` VARCHAR(100) NOT NULL,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `TIPO_DOC_ID` VARCHAR(10) NOT NULL,
  `NUMERO_DOC_ID` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `PASSWORD_ACTIVA`  BOOLEAN DEFAULT FALSE,
  `PASSWORD_AUTENTICACION` VARCHAR(100) DEFAULT NULL,
  `ACTIVO` BOOLEAN DEFAULT FALSE,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  `FECHA_ACTUALIZACION` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION` TIME DEFAULT NULL,
  `FECHA_ACTUALIZACION_PASSWORD` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION_PASSWORD` TIME DEFAULT NULL,
  PRIMARY KEY(ID_USUARIO, EMAIL)
);

/*TABLA MICROSERVICIOS*/
DROP TABLE IF EXISTS `MICROSERVICIOS`;
CREATE TABLE `MICROSERVICIOS` (
  `ID_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `NOMBRE_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `DETALLES` VARCHAR(1000) NOT NULL,
  `URL_MICROSERVICIO` VARCHAR(1000) NOT NULL,
  `ALIAS_MICROSERIVICIO` VARCHAR(100) NOT NULL,
  `URL_ALIAS_MICROSERVICIO` VARCHAR(1000) NOT NULL,
  `ICON_MICROSERVICIO` VARCHAR(100) DEFAULT NULL;
  `ORDEN` INT(10) NOT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  `FECHA_ACTUALIZACION` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION` TIME DEFAULT NULL,
  PRIMARY KEY(ID_MICROSERVICIO, NOMBRE_MICROSERVICIO)
);

/*TABLA ROLES*/
DROP TABLE IF EXISTS `MODULO`;
CREATE TABLE `MODULO` (
  `ID_MODULO` VARCHAR(100) NOT NULL,
  `NOMBRE_MODULO` VARCHAR(100) NOT NULL,
  `DETALLES` VARCHAR(1000) NOT NULL,
  `URL_MODULO` VARCHAR(1000) NOT NULL,
  `ALIAS_MODULO` VARCHAR(100) NOT NULL,
  `URL_ALIAS_MODULO` VARCHAR(1000) NOT NULL,
  `ICON_MODULO` VARCHAR(100) DEFAULT NULL;
  `ORDEN` INT(10) NOT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  `FECHA_ACTUALIZACION` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION` TIME DEFAULT NULL,
  PRIMARY KEY(ID_MODULO, NOMBRE_MODULO)
);

/*TABLA CONFIGURACION_MICROSERVICIOS_MODULOS*/
DROP TABLE IF EXISTS `CONFIGURACION_MICROSERVICIOS_MODULOS`;
CREATE TABLE `CONFIGURACION_MICROSERVICIOS_MODULOS` (
  `ID_CONFIGURACION` VARCHAR(100) NOT NULL,
  `ID_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `NOMBRE_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `ID_MODULO` VARCHAR(100) NOT NULL,
  `NOMBRE_MODULO` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  PRIMARY KEY(ID_CONFIGURACION),
  FOREIGN KEY (ID_MICROSERVICIO, NOMBRE_MICROSERVICIO) REFERENCES MICROSERVICIOS(ID_MICROSERVICIO, NOMBRE_MICROSERVICIO) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (ID_MODULO, NOMBRE_MODULO) REFERENCES MODULO(ID_MODULO, NOMBRE_MODULO) ON UPDATE CASCADE ON DELETE CASCADE
);

/*TABLA CONFIGURACION_USUARIOS*/
DROP TABLE IF EXISTS `CONFIGURACION_USUARIOS`;
CREATE TABLE `CONFIGURACION_USUARIOS` (
  `ID_CONFIGURACION_USUARIO` VARCHAR(100) NOT NULL,
  `ID_USUARIO` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `ID_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `NOMBRE_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `ID_MODULO` VARCHAR(100) NOT NULL,
  `NOMBRE_MODULO` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  PRIMARY KEY(ID_CONFIGURACION_USUARIO),
  FOREIGN KEY (ID_USUARIO, EMAIL) REFERENCES USUARIOS(ID_USUARIO, EMAIL) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (ID_MICROSERVICIO, NOMBRE_MICROSERVICIO) REFERENCES MICROSERVICIOS(ID_MICROSERVICIO, NOMBRE_MICROSERVICIO) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (ID_MODULO, NOMBRE_MODULO) REFERENCES MODULO(ID_MODULO, NOMBRE_MODULO) ON UPDATE CASCADE ON DELETE CASCADE
);

/*TABLA ROLES*/
CREATE TABLE IF NOT EXISTS `ROLES` (
  `ID_ROL` VARCHAR(100) NOT NULL,
  `NOMBRE_ROL` VARCHAR(100) NOT NULL,
  `DETALLES` VARCHAR(1000) NOT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  `FECHA_ACTUALIZACION` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION` TIME DEFAULT NULL,
  PRIMARY KEY (ID_ROL, NOMBRE_ROL)
);

/*TABLA CONFIGURAICON_ROLES*/
CREATE TABLE IF NOT EXISTS `CONFIGURACION_ROLES` (
  `ID_CONFIGURACION_ROLES`VARCHAR(100) NOT NULL,
  `ID_USUARIO` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `ID_ROL` VARCHAR(100) NOT NULL,
  `NOMBRE_ROL` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  PRIMARY KEY (ID_CONFIGURACION_ROLES),
  FOREIGN KEY (ID_USUARIO, EMAIL) REFERENCES USUARIOS(ID_USUARIO, EMAIL) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (ID_ROL, NOMBRE_ROL) REFERENCES ROLES(ID_ROL, NOMBRE_ROL)  ON UPDATE CASCADE ON DELETE CASCADE
);

/* TABLA DISPOSITIVOS */
CREATE TABLE `DISPOSITIVOS` (
  `ID_DISPOSITIVO` VARCHAR(100) NOT NULL,
  `TOKEN` LONGTEXT NOT NULL,
  `MARCA` VARCHAR(100) NOT NULL,
  `REFERENCIA` VARCHAR(10) NOT NULL,
  `LATITUD` VARCHAR(50) NOT NULL,
  `LONGITUD` VARCHAR(100) NOT NULL,
  `ID_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `NOMBRE_MICROSERVICIO` VARCHAR(100) NOT NULL,
  `EMAIL_RESPONSABLE` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `PASSWORD_ACTIVA`  BOOLEAN DEFAULT FALSE,
  `PASSWORD_AUTENTICACION` VARCHAR(100) DEFAULT NULL,
  `DISPOSITIVO_ACTIVO` BOOLEAN DEFAULT FALSE,
  `FECHA_ACTUALIZACION_PASSWORD` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION_PASSWORD` TIME DEFAULT NULL,
  `FECHA_CREACION` DATE NOT NULL,
  `HORA_CREACION` TIME NOT NULL,
  `FECHA_ACTUALIZACION` DATE DEFAULT NULL,
  `HORA_ACTUALIZACION` TIME DEFAULT NULL,
  PRIMARY KEY(ID_DISPOSITIVO),
  FOREIGN KEY (ID_MICROSERVICIO, NOMBRE_MICROSERVICIO) REFERENCES MICROSERVICIOS(ID_MICROSERVICIO, NOMBRE_MICROSERVICIO) ON UPDATE CASCADE ON DELETE CASCADE
);
