/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          25/01/2021
    Ejecutar en:    Script para Dockerfile
    Descripción:    Crear permisos sobre las tablas para el usuario DBATEST
*/

GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.NODO_SENSOR TO 'DBATEST'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.VARIABLES_NODO_SENSOR TO 'DBATEST'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.CONFIGURACION_VARIABLES_NODO_SENSOR TO 'DBATEST'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.REGLAS_NODO_SENSOR TO 'DBATEST'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.DATOS_NODO_SENSOR TO 'DBATEST'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.ERRORES_LOG_EJECUCION TO 'DBATEST'@'%'; 
GRANT SELECT, INSERT ON PROYECTO_GRADO_API_TEST.REPORTE_LOG_EJECUCION TO 'DBATEST'@'%';
FLUSH PRIVILEGES;