/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          25/01/2021
    Ejecutar en:    Script para Dockerfile
    Descripción:    Crear permisos sobre las tablas para el usuario DBAPROD
*/

GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.NODO_SENSOR TO 'DBAPROD'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.VARIABLES_NODO_SENSOR TO 'DBAPROD'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.CONFIGURACION_VARIABLES_NODO_SENSOR TO 'DBAPROD'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.REGLAS_NODO_SENSOR TO 'DBAPROD'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.DATOS_NODO_SENSOR TO 'DBAPROD'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.ERRORES_LOG_EJECUCION TO 'DBAPROD'@'%'; 
GRANT SELECT, INSERT ON PROYECTO_GRADO_API_PROD.REPORTE_LOG_EJECUCION TO 'DBAPROD'@'%';
FLUSH PRIVILEGES;