/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          25/01/2021
    Ejecutar en:    Script para Dockerfile
    Descripción:    Crear permisos sobre las tablas para el usuario DBADEV
*/

GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_DEV.NODO_SENSOR TO 'DBADEV'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_DEV.VARIABLES_NODO_SENSOR TO 'DBADEV'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_DEV.CONFIGURACION_VARIABLES_NODO_SENSOR TO 'DBADEV'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_DEV.REGLAS_NODO_SENSOR TO 'DBADEV'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_DEV.DATOS_NODO_SENSOR TO 'DBADEV'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_DEV.ERRORES_LOG_EJECUCION TO 'DBADEV'@'%'; 
GRANT SELECT, INSERT ON PROYECTO_GRADO_API_DEV.REPORTE_LOG_EJECUCION TO 'DBADEV'@'%';
FLUSH PRIVILEGES;