/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          16/12/2020
    Ejecutar en:    BD_Proyecto_Grado
    Descripción:    Crear tabla DATOS_NODO_SENSOR.
*/

CREATE TABLE IF NOT EXISTS `DATOS_NODO_SENSOR` (
	`ID_DATO` int(11) NOT NULL AUTO_INCREMENT,
	`ID_NODO_SENSOR` int not null, 
	`ID_VARIABLE` int not null,
	`NOMBRE_VARIABLE` varchar(300) NOT NULL,
	`VALOR_DATO` varchar(10) not null,
	`VALOR_NOTIFICADO` bool DEFAULT FALSE,
	`ID_REGLA` int DEFAULT null,
	`EXPRESION_EVALUADA` varchar(300) DEFAULT NULL,
	`FECHA_CREACION` date NOT NULL,
	`HORA_CREACION` time NOT NULL,
	primary key (ID_DATO),
	FOREIGN key (ID_NODO_SENSOR) REFERENCES NODO_SENSOR(ID_NODO_SENSOR) ON UPDATE CASCADE ON DELETE CASCADE,
  	FOREIGN key (ID_VARIABLE, NOMBRE_VARIABLE) REFERENCES VARIABLES_NODO_SENSOR(ID_VARIABLE, NOMBRE_VARIABLE) ON UPDATE CASCADE ON DELETE cascade,
	FOREIGN key (ID_REGLA) REFERENCES REGLAS_NODO_SENSOR(ID_REGLA) ON UPDATE CASCADE ON DELETE CASCADE
);
