/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          12/01/2021
    Ejecutar en:    Servidor BD 
    Descripción:    Asiganar permisos a base de datos
*/

--Asignar permisos ambiente DESARROLLO

--Asignar permisos ambiente PROD
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.NODO_SENSOR TO 'DBAPROD'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.VARIABLES_NODO_SENSOR TO 'DBAPROD'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.CONFIGURACION_VARIABLES_NODO_SENSOR TO 'DBAPROD'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.REGLAS_NODO_SENSOR TO 'DBAPROD'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.DATOS_NODO_SENSOR TO 'DBAPROD'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_PROD.ERRORES_LOG_EJECUCION TO 'DBAPROD'@'%'; 
GRANT SELECT, INSERT ON PROYECTO_GRADO_API_PROD.REPORTE_LOG_EJECUCION TO 'DBAPROD'@'%';
FLUSH PRIVILEGES;