/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          12/01/2021
    Ejecutar en:    Servidor BD 
    Descripción:    Asiganar permisos a base de datos
*/

--Asignar permisos ambiente DESARROLLO

--Asignar permisos ambiente TEST
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.NODO_SENSOR TO 'DBATEST'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.VARIABLES_NODO_SENSOR TO 'DBATEST'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.CONFIGURACION_VARIABLES_NODO_SENSOR TO 'DBATEST'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.REGLAS_NODO_SENSOR TO 'DBATEST'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.DATOS_NODO_SENSOR TO 'DBATEST'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTO_GRADO_API_TEST.ERRORES_LOG_EJECUCION TO 'DBATEST'@'%'; 
GRANT SELECT, INSERT ON PROYECTO_GRADO_API_TEST.REPORTE_LOG_EJECUCION TO 'DBATEST'@'%';
FLUSH PRIVILEGES;