/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          22/12/2020
    Ejecutar en:    BD_Proyecto_Grado
    Descripción:    Query para configurar los roles
*/

--Crear una nueva configuración rol
INSERT
    INTO CONFIGURACION_ROLES
    (ID_USER, ID_ROL, FECHA_CREACION, HORA_CREACION)
VALUES 
    (?, ?, CURDATE(), CURTIME())

--Comprobar si el usuario y el rol existe

SELECT 
    (SELECT COUNT(*) FROM USER WHERE ID_USER = ?) USER_EXIST,
    (SELECT COUNT(*) FROM ROLES WHERE ID_ROL = ?) ROL_EXIST
FROM DUAL

SELECT 
    CASE
        WHEN (SELECT COUNT(*) FROM USER WHERE ID_USER = ?) <> 0 THEN TRUE
        ELSE FALSE
    END USER_EXIST,
    CASE 
        WHEN (SELECT COUNT(*) FROM ROLES WHERE ID_ROL = ?) <> 0 THEN TRUE
        ELSE FALSE
    END ROL_EXIST
FROM DUAL

--Comprobar si la configuracion ya existe 
SELECT * FROM CONFIGURACION_ROLES
    WHERE ID_USER = ? AND ID_ROL = ?

--Consultar los roles asignados a un usuario para validar que peticiones puede consumir
SELECT 
    U.ID_USER,
	U.NOMBRES, 
	U.APELLIDOS, 
	U.TIPO_DOC_ID, 
	U.NUMERO_DOC_ID, 
	U.EMAIL,
	U.PASSWORD, 
	CR.ID_ROL, 
	(SELECT 
		NOMBRE_ROL 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) NOMBRE_ROL, 
	(SELECT 
		DETALLES 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) DETALLES_ROL, 
	U.FECHA_CREACION, 
	U.HORA_CREACION
FROM USER U 
INNER JOIN 
	CONFIGURACION_ROLES CR 
	ON U.ID_USER = CR.ID_USER;

--Consultar los roles asiganados a un usuario
SELECT 
	U.ID_USER,
	U.NOMBRES, 
	U.APELLIDOS, 
	U.TIPO_DOC_ID, 
	U.NUMERO_DOC_ID, 
	CR.ID_CONFIGURACION,
	CR.ID_ROL, 
	(SELECT 
		NOMBRE_ROL 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) NOMBRE_ROL, 
	(SELECT 
		DETALLES 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) DETALLES_ROL, 
	U.FECHA_CREACION, 
	U.HORA_CREACION
FROM USER U 
INNER JOIN 
	CONFIGURACION_ROLES CR 
	ON U.ID_USER = CR.ID_USER;


--Consultar por nombre rol
SELECT 
	U.ID_USER,
	U.NOMBRES, 
	U.APELLIDOS, 
	U.TIPO_DOC_ID, 
	U.NUMERO_DOC_ID, 
	CR.ID_CONFIGURACION,
	CR.ID_ROL, 
	(SELECT 
		NOMBRE_ROL 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) NOMBRE_ROL, 
	(SELECT 
		DETALLES 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) DETALLES_ROL, 
	U.FECHA_CREACION, 
	U.HORA_CREACION
FROM USER U 
INNER JOIN 
	CONFIGURACION_ROLES CR 
	ON U.ID_USER = CR.ID_USER
WHERE 
    ID_ROL = (SELECT ID_ROL FROM ROLES R WHERE R.NOMBRE_ROL = 'ADMINISTRADOR');

--Consultar por mail usuario
SELECT 
	U.ID_USER,
	U.NOMBRES, 
	U.APELLIDOS, 
	U.TIPO_DOC_ID, 
	U.NUMERO_DOC_ID, 
	CR.ID_CONFIGURACION,
	CR.ID_ROL, 
	(SELECT 
		NOMBRE_ROL 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) NOMBRE_ROL, 
	(SELECT 
		DETALLES 
	FROM ROLES R 
	WHERE ID_ROL = CR.ID_ROL) DETALLES_ROL, 
	U.FECHA_CREACION, 
	U.HORA_CREACION
FROM USER U 
INNER JOIN 
	CONFIGURACION_ROLES CR 
	ON U.ID_USER = CR.ID_USER
WHERE 
    U.EMAIL = 'juanes@mail.com';

--Consultar configuracion de rol creada por ID
SELECT * FROM CONFIGURACION_ROLES 
	WHERE ID_CONFIGURACION = 5;

--Eliminar configuración de rol creada por ID
DELETE FROM CONFIGURACION_ROLES 
    WHERE ID_CONFIGURACION = ?;