/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          17/01/2021
    Ejecutar en:    BD_Proyecto_Grado
    Descripción:    Query para configurar las reglas de las variables y nodo sensor
*/

--Consultar existencia nodo sensor y variable
SELECT 
    (SELECT COUNT(*) FROM NODO_SENSOR WHERE ID_NODO_SENSOR = ?) NODO_SENSOR_EXIST,
    (SELECT COUNT(*) FROM VARIABLES_NODO_SENSOR WHERE NOMBRE_VARIABLE = ? ) VARIABLE_EXIST
FROM dual

--Verificar la existencia de la regla 
SELECT * FROM REGLAS_NODO_SENSOR
    WHERE ID_NODO_SENSOR = ? AND NOMBRE_VARIABLE = ?

--Insertar datos
INSERT
    INTO REGLAS_NODO_SENSOR 
    (ID_NODO_SENSOR, ID_VARIABLE, NOMBRE_VARIABLE, EXPRESION, FECHA_CREACION, HORA_CREACION)
VALUES (?, (SELECT ID_VARIABLE FROM VARIABLES_NODO_SENSOR WHERE NOMBRE_VARIABLE = ?), ?, ?, CURDATE(), CURTIME());

INSERT
    INTO REGLAS_NODO_SENSOR 
    (ID_NODO_SENSOR, ID_VARIABLE, NOMBRE_VARIABLE, EXPRESION, FECHA_CREACION, HORA_CREACION)
VALUES (?, ?, (SELECT NOMBRE_VARIABLE FROM VARIABLES_NODO_SENSOR WHERE ID_VARIABLE = ?), ?, CURDATE(), CURTIME());
