/*
    Autor:          Juan Esteban Nichoy Larrañaga
    Fecha:          30/12/2020
    Ejecutar en:    BD_Proyecto_Grado
    Descripción:    Query para los datos de los nodos sensores
*/

--Comprobar la existencia del nodo sensor
SELECT * FROM NODO_SENSOR
    WHERE ID_NODO_SENSOR = ?

--Consultar variables configuradas para el nodo sensor
SELECT
	CVNS.ID_CONFIGURACION,
	NS.ID_NODO_SENSOR,
	CVNS.ID_VARIABLE,
	(SELECT 
		VNS.NOMBRE_VARIABLE 
	FROM VARIABLES_NODO_SENSOR VNS  
	WHERE ID_VARIABLE = CVNS.ID_VARIABLE) NOMBRE_VARIABLE,
	CVNS.FECHA_CREACION FECHA_CREACION_CONFIGURACION,
	CVNS.HORA_CREACION HORA_CREACION_CONFIGURACION
FROM NODO_SENSOR NS
INNER JOIN 
	CONFIGURACION_VARIABLES_NODO_SENSOR CVNS 
	ON NS.ID_NODO_SENSOR = CVNS.ID_NODO_SENSOR 
	where NS.ID_NODO_SENSOR = ?

--Insertar datos
INSERT 
    INTO DATOS_NODO_SENSOR
    (ID_NODO_SENSOR, ID_VARIABLE, VALOR_DATO, FECHA_CREACION, HORA_CREACION)
VALUES 
    (
        1,
        (SELECT ID_VARIABLE FROM VARIABLES_NODO_SENSOR WHERE NOMBRE_VARIABLE = 'TEMPERATURA AGUA'),
        "13.8",
        CURDATE(),
        CURTIME()
    );